env:
  browser: true
  es2020: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'airbnb-base'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules: {
  'allowAfterThis': true,
  'allowAfterSuper': true,
  'allowAfterThisConstructor': true,
  'enforceInMethodNames': true
  }
